import { StagewiseDevToolbar } from '../stagewise-toolbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import { ToasterProvider } from '@/components/providers/ToasterProvider'
import { AuthProvider } from '@/contexts/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AI Pic Center',
  description: 'Generated by nextjs',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh">
      <body className={inter.className}>
        <StagewiseDevToolbar />
        <AuthProvider>
          <Header />
          <ToasterProvider />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}